export const ADD_ITEM = "DOM/ADD_ITEM"

export const LIST_FETCH_REQUESTED = "STORE/LIST_FETCH_REQUESTED"
export const LIST_FETCH_SUCCEEDED = "STORE/LIST_FETCH_SUCCEEDED"
export const LIST_FETCH_FAILED = "STORE/USER_FETCH_FAILED"
