export const LIST_FETCH_REQUESTED = "STORE/LIST_FETCH_REQUESTED"
export const LIST_FETCH_SUCCEEDED = "STORE/LIST_FETCH_SUCCEEDED"
export const LIST_FETCH_FAILED = "STORE/USER_FETCH_FAILED"

export const LIST_FILTER_BY_NAME = "STORE/LIST_FILTER_BY_NAME"
export const LIST_FILTER_BY_NUMBER = "STORE/LIST_FILTER_BY_NUMBER"

export const CREATE_FORM_ITEM = "FORM/CREATE_FORM_ITEM"
export const EDIT_FORM_ITEM = "FORM/EDIT_FORM_ITEM"
export const DELETE_FORM_ITEM = "FORM/DELETE_FORM_ITEM"

export const CREATE_NEW_ACCOUNT = "DOM/CREATE_NEW_ACCOUNT"
